apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-svc"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: "{{ .Release.Name }}"
{{ with .Values.service.annotations }}
  annotations:
{{ toYaml  . | indent 4}}
{{ end }}
spec:
  type: "{{ .Values.service.type }}"
{{ with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml  . | indent 4 }}
{{ end }}
  ports:
  {{- range .Values.tcp_ports }}
  - port: {{ . }}
    targetPort: {{ . }}
    protocol: TCP
    name: "port-{{ . }}"
  {{- end }}
  selector:
    app: "{{ .Release.Name }}"
